name = "da-admin"
main = "src/index.js"
compatibility_date = "2023-10-30"

vars = { DA_COLLAB = "https://collab.da.live" }
kv_namespaces = [
  { binding = "DA_AUTH", id = "d6217b7c63ef40889583ba5c080c3908" },
  { binding = "DA_CONFIG", id = "feb8618620bb4ca3a866f1c71adbe8ef" }
]

[env.stage]
vars = { ENVIRONMENT = "stage", DA_COLLAB = "https://collab.da.live" }
kv_namespaces = [
  { binding = "DA_AUTH", id = "21693f3b20f54fcbb850ddc8947335ba" },
  { binding = "DA_CONFIG", id = "c44cb8dc69f041dc87c5aaef41b97df9" }
]


[env.dev]
vars = { ENVIRONMENT = "dev", DA_COLLAB = "http://localhost:4711" }
kv_namespaces = [
  { binding = "DA_AUTH", id = "21693f3b20f54fcbb850ddc8947335ba" },
  { binding = "DA_CONFIG", id = "c44cb8dc69f041dc87c5aaef41b97df9" }
]
